# Data Cleaning

## Import libraries

In [52]:
import pandas as pd
import numpy as np

## Load Data

In [3]:
df = pd.read_csv('data/hotel_booking.csv')
df.shape

(119390, 36)

In [4]:
pd.options.display.max_columns = None   #para que muestren todas las columnas
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

## Clean Data
- Use all features?
- Null values? Drop, mean, median, mode, ...
- Duplicated values? (see "duplicated" and "drop_duplicates" functions in pandas)
- Outliers.

### NaNs

#### Inspection

In [6]:
# NaN values
nan_ser = df.isna().sum().sort_values(ascending=False)
nan_ser[nan_ser > 0]

company     112593
agent        16340
country        488
children         4
dtype: int64

In [7]:
df["children"].value_counts()

0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: children, dtype: int64

In [8]:
df[df['children'].isna()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
40600,City Hotel,1,2,2015,August,32,3,1,0,2,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-01,Craig Campos,CraigCampos@mail.com,820-622-9854,************7219
40667,City Hotel,1,1,2015,August,32,5,0,2,2,NaN,0,BB,PRT,Direct,Undefined,0,0,0,B,B,0,No Deposit,14.0,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-04,David Murphy,David.Murphy94@yahoo.com,231-438-6733,************8925
40679,City Hotel,1,1,2015,August,32,5,0,2,3,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,18.0,0,2,Canceled,2015-08-04,Frank Burton,Frank.Burton@comcast.net,395-084-3601,************6190
41160,City Hotel,1,8,2015,August,33,13,2,5,2,NaN,0,BB,PRT,Online TA,Undefined,0,0,0,B,B,0,No Deposit,9.0,NaN,0,Transient-Party,76.5,0,1,Canceled,2015-08-09,Jerry Roberts,JRoberts@hotmail.com,979-355-3554,************5648

Cambiamos los 4 nulos de children al valor 0.0 que es el que tiene la mayoria, ya que afectara poco al resultado

In [9]:
df.loc[df['children'].isna(), 'children'] = 0.0

In [10]:
df["country"].value_counts()

PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: country, Length: 177, dtype: int64

In [11]:
df[df['country'].isna()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
30,Resort Hotel,0,118,2015,July,27,1,4,10,1,0.0,0,BB,NaN,Direct,Direct,0,0,0,A,A,2,No Deposit,NaN,NaN,0,Transient,62.0,0,2,Check-Out,2015-07-15,Diamond Wilson,Wilson.Diamond@comcast.net,870-563-6202,************8017
4127,Resort Hotel,1,0,2016,February,8,15,0,0,0,0.0,0,SC,NaN,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,NaN,383.0,0,Transient,0.0,0,0,Canceled,2016-02-15,Alex Lang,Lang_Alex@mail.com,479-339-8268,************4034
7092,Resort Hotel,1,8,2016,July,30,21,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,204.0,0,Transient,73.0,0,2,Canceled,2016-07-20,Tamara Olson,Tamara_O@gmail.com,926-236-0559,************9899
7860,Resort Hotel,1,39,2016,August,36,30,0,5,2,0.0,0,HB,NaN,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Transient,159.0,0,5,Canceled,2016-07-22,Amanda Harper,Amanda.H66@yahoo.com,864-257-9807,************9835
8779,Resort Hotel,1,0,2016,October,42,13,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,457.0,0,Transient,50.0,0,0,Canceled,2016-10-13,Shelley Jenkins,Jenkins_Shelley@yahoo.com,621-092-0324,************9962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65908,City Hotel,1,0,2017,April,15,10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,P,P,0,No Deposit,NaN,279.0,0,Transient,0.0,0,0,Canceled,2017-04-10,Robin Diaz,Diaz.Robin@yandex.com,358-814-7268,************2947
65909,City Hotel,1,0,2017,April,15,10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,P,P,0,No Deposit,NaN,279.0,0,Transient,0.0,0,0,Canceled,2017-04-10,Teresa Duncan,TeresaDuncan@att.com,636-547-8162,************8374
65910,City Hotel,1,0,2017,April,15,10,0,0,0,0.0,0,SC,NaN,Complementary,Corporate,0,0,0,P,P,0,No Deposit,NaN,279.0,0,Transient,0.0,0,0,Canceled,2017-04-10,Michael Gonzalez,Michael_Gonzalez@protonmail.com,472-826-7082,************2498
80830,City Hotel,0,4,2015,November,48,23,1,2,1,0.0,0,BB,NaN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,37.0,NaN,0,Transient-Party,70.0,0,0,Check-Out,2015-11-26,Alice Campbell,Alice.C@gmail.com,795-315-2254,************2426
101488,City Hotel,0,1,2016,November,47,13,2,2,2,0.0,0,BB,NaN,Direct,Direct,0,0,0,A,A,0,No Deposit,14.0,NaN,0,Group,105.0,0,1,Check-Out,2016-11-17,Kelly Meza,Kelly_M84@zoho.com,471-936-7807,************7105

Cambiamos los nulos a "No Country" ya que no sabemos de que pais son

In [12]:
df.loc[df['country'].isna(), 'country'] = "No Country"

In [13]:
'''
total = df["country"].value_counts().sum()
first = 48590 * 100 / total
second = 12129 * 100 / total
third = 10415 * 100 / total
perc_total = first + second + third
new_first = (first / perc_total) * 100
new_second = (second / perc_total) * 100
new_third = (third / perc_total) * 100
print(new_first, new_second, new_third)
change_null1 = 488 * new_first / 100
change_null2 = 488 * new_second / 100
change_null3 = 488 * new_third / 100
print(change_null1, change_null2, change_null3)
print(int(change_null1) + 1 + int(change_null2) + int(change_null3))
'''

'\ntotal = df["country"].value_counts().sum()\nfirst = 48590 * 100 / total\nsecond = 12129 * 100 / total\nthird = 10415 * 100 / total\nperc_total = first + second + third\nnew_first = (first / perc_total) * 100\nnew_second = (second / perc_total) * 100\nnew_third = (third / perc_total) * 100\nprint(new_first, new_second, new_third)\nchange_null1 = 488 * new_first / 100\nchange_null2 = 488 * new_second / 100\nchange_null3 = 488 * new_third / 100\nprint(change_null1, change_null2, change_null3)\nprint(int(change_null1) + 1 + int(change_null2) + int(change_null3))\n'

In [14]:
# Testing
'''
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
imputer.fit(df['country'])
X_imputed = imputer.transform(df['country'])
'''

"\nfrom sklearn.impute import KNNImputer\n\nimputer = KNNImputer(n_neighbors=5)\nimputer.fit(df['country'])\nX_imputed = imputer.transform(df['country'])\n"

In [15]:
#import random

In [16]:
'''
values = ["PRT"] * 334 + ["GBR"] * 83 + ["FRA"] * 71
random.shuffle(values)
mask = df["country"].isnull()  
df.loc[mask, "country"] = values 
'''

'\nvalues = ["PRT"] * 334 + ["GBR"] * 83 + ["FRA"] * 71\nrandom.shuffle(values)\nmask = df["country"].isnull()  \ndf.loc[mask, "country"] = values \n'

In [17]:
nan_ser = df.isna().sum().sort_values(ascending=False)
nan_ser[nan_ser > 0]

company    112593
agent       16340
dtype: int64

In [18]:
df["agent"].value_counts()

9.0      31961
240.0    13922
1.0       7191
14.0      3640
7.0       3539
         ...
289.0        1
432.0        1
265.0        1
93.0         1
304.0        1
Name: agent, Length: 333, dtype: int64

In [19]:
df[df['agent'].isna()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03,Dylan Rangel,Rangel.Dylan@comcast.net,420-332-5209,************6994
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,G,0,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02,Curtis Rodriguez,CRodriguez@verizon.com,466-424-2102,************1179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119124,City Hotel,0,0,2017,August,35,29,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,A,0,No Deposit,NaN,72.0,0,Transient,0.00,0,2,Check-Out,2017-08-30,Erin Hatfield,EHatfield@aol.com,868-960-2621,************8605
119151,City Hotel,0,0,2017,August,35,29,0,1,2,2.0,0,BB,NLD,Direct,Direct,0,0,0,G,G,0,No Deposit,NaN,NaN,0,Transient,270.00,0,0,Check-Out,2017-08-30,Jennifer Douglas,JDouglas66@yahoo.com,864-987-8957,************4027
119166,City Hotel,0,0,2017,August,35,30,0,1,1,0.0,0,BB,BRA,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Transient,140.00,0,0,Check-Out,2017-08-31,Sarah Miller,Sarah_Miller57@verizon.com,498-486-6867,************4194
119215,City Hotel,0,2,2017,August,35,31,0,1,1,0.0,0,SC,LBN,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Transient,140.00,0,2,Check-Out,2017-09-01,George Marquez,George_M@xfinity.com,303-344-4582,************9925
119248,City Hotel,0,22,2017,August,35,29,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,485.0,0,Transient,75.00,0,4,Check-Out,2017-09-01,Tammy Hughes,Tammy_H@outlook.com,992-779-1181,************3098

Los agent nulls que que tienen un "customer_type" de "Transient" o "Transient-Party" les ponemos 0.0 ya que no tendrian agente

In [20]:
condicion = (df["agent"].isna()) & (df["customer_type"].isin(["Transient", "Transient-Party"]))
df.loc[condicion, "agent"] = df.loc[condicion, "agent"].fillna("0.0")

In [21]:
nan_ser = df.isna().sum().sort_values(ascending=False)
nan_ser[nan_ser > 0]

company    112593
agent         112
dtype: int64

In [22]:
df[df['agent'].isna()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
541,Resort Hotel,0,0,2015,July,30,19,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,NaN,240.0,0,Group,88.2,0,0,Check-Out,2015-07-20,Anne Alvarez,Anne_A@comcast.net,514-458-1755,************6603
1539,Resort Hotel,1,304,2015,September,36,3,0,3,40,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,0.0,0,0,Canceled,2015-01-02,Brianna Mejia,BriannaMejia@gmail.com,579-877-3361,************5189
1643,Resort Hotel,1,336,2015,September,37,7,1,2,50,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,0.0,0,0,Canceled,2015-01-18,Timothy Clark,Timothy.Clark@comcast.net,902-620-3655,************5474
1917,Resort Hotel,1,349,2015,September,39,21,1,3,27,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,0.0,0,0,Canceled,2015-01-02,Benjamin Pierce,Pierce.Benjamin78@zoho.com,589-933-9273,************2856
1962,Resort Hotel,1,352,2015,September,39,24,1,3,27,0.0,0,HB,PRT,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,0.0,0,0,Canceled,2015-01-02,James Miller,James.Miller@gmail.com,295-483-3334,************6124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109344,City Hotel,0,0,2017,April,15,10,1,0,2,0.0,0,BB,POL,Direct,TA/TO,1,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,126.0,0,4,Check-Out,2017-04-11,Christy Spears,Christy.S90@aol.com,460-531-6597,************5125
114281,City Hotel,0,3,2017,June,25,19,1,0,2,0.0,0,BB,USA,Direct,TA/TO,0,0,0,D,D,0,No Deposit,NaN,NaN,0,Group,130.0,0,0,Check-Out,2017-06-20,Peter Miller,Miller.Peter@gmail.com,488-631-4006,************2636
114343,City Hotel,0,2,2017,June,25,20,0,1,2,0.0,0,SC,FRA,Direct,TA/TO,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,150.0,0,0,Check-Out,2017-06-21,Cindy Snyder,CSnyder@xfinity.com,738-695-1397,************2388
115822,City Hotel,0,70,2017,July,28,11,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,NaN,NaN,0,Group,120.0,0,1,Check-Out,2017-07-12,Jennifer Alvarado,Jennifer_Alvarado@gmail.com,872-804-7817,************5638
115823,City Hotel,0,70,2017,July,28,11,0,1,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Group,120.0,0,1,Check-Out,2017-07-12,Ashley Davidson,Ashley_Davidson@mail.com,679-023-8356,************1992

In [23]:
df[df['agent'].isna()].loc[df[df['agent'].isna()]["customer_type"] != "Group"]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
2262,Resort Hotel,0,44,2015,October,41,8,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Contract,50.00,0,0,Check-Out,2015-10-11,Allison Ellis,Allison.Ellis@yahoo.com,890-312-6941,************9275
2265,Resort Hotel,0,44,2015,October,41,8,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,NaN,NaN,0,Contract,50.00,0,0,Check-Out,2015-10-11,Leslie Gallegos,LGallegos53@att.com,822-842-1040,************8266
17422,Resort Hotel,0,43,2015,October,41,7,0,4,3,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,2,No Deposit,NaN,NaN,0,Contract,80.00,0,1,Check-Out,2015-10-11,Douglas Wright,Douglas.Wright@outlook.com,562-257-4991,************1140
17428,Resort Hotel,0,7,2015,October,41,9,0,2,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Contract,50.00,0,1,Check-Out,2015-10-11,Samantha Joseph,SamanthaJoseph@hotmail.com,790-153-7857,************5903
17440,Resort Hotel,0,44,2015,October,41,8,0,3,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,1,No Deposit,NaN,NaN,0,Contract,50.00,0,0,Check-Out,2015-10-11,Carrie Smith,Carrie_Smith34@verizon.com,855-862-9572,************1172
28438,Resort Hotel,0,2,2016,October,41,3,1,2,1,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,D,D,0,No Deposit,NaN,NaN,0,Contract,100.00,0,0,Check-Out,2016-10-06,Daniel Munoz,DanielMunoz69@gmail.com,540-234-3436,************8445
41139,City Hotel,0,0,2015,August,33,13,0,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,K,0,No Deposit,NaN,NaN,0,Contract,0.00,0,2,Check-Out,2015-08-13,Amber Young,Amber.Y32@comcast.net,412-079-1701,************2146
41618,City Hotel,0,0,2015,August,34,19,3,9,2,0.0,0,BB,AGO,Online TA,TA/TO,0,0,0,A,D,2,No Deposit,NaN,NaN,0,Contract,106.84,0,2,Check-Out,2015-08-31,Alyssa Hampton,Alyssa.Hampton46@verizon.com,308-399-1627,************7185
42940,City Hotel,0,9,2015,September,37,11,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,A,D,0,No Deposit,NaN,NaN,0,Contract,105.00,0,2,Check-Out,2015-09-12,Amanda Lopez,ALopez@verizon.com,157-602-7921,************9441
43082,City Hotel,0,6,2015,September,38,14,1,2,1,1.0,0,BB,PRT,Online TA,Direct,0,0,0,A,A,7,No Deposit,NaN,NaN,0,Contract,109.00,0,2,Check-Out,2015-09-17,Anne Henderson,Anne.Henderson@verizon.com,261-661-1178,************3617
77001,City Hotel,0,0,2015,August,35,26,0,1,0,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,F,B,0,No Deposit,NaN,NaN,0,Contract,0.00,0,2,Check-Out,2015-08-27,Jennifer Nelson,Jennifer_Nelson75@xfinity.com,662-104-2747,************5301
77003,City Hotel,0,0,2015,August,35,27,0,1,0,0.0,0,BB,PRT,Online TA,Direct,1,0,0,F,B,0,No Deposit,NaN,NaN,0,Contract,0.00,0,2,Check-Out,2015-08-28,Melanie Mcknight,Melanie_M@yahoo.com,436-308-2427,************3330
86041,City Hotel,0,130,2016,March,13,25,0,1,0,2.0,0,BB,ITA,Complementary,Direct,0,0,0,A,D,1,No Deposit,NaN,NaN,0,Contract,6.00,0,2,Check-Out,2016-03-26,Taylor Moore,TMoore64@protonmail.com,660-882-5148,************4740

Los agent que quedan en null los dejamos en -1.0 ya que son diferentes, ya que si tienen contract o van en group, pero no tienen agent

In [24]:
df.loc[df['agent'].isna(), 'agent'] = -1.0   # customer_type = contract & customer_type = Group

In [25]:
df[df['company'].notna()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,0.0,0,BB,FRA,Corporate,Corporate,0,0,0,A,G,0,No Deposit,0.0,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02,Curtis Rodriguez,CRodriguez@verizon.com,466-424-2102,************1179
218,Resort Hotel,1,1,2015,July,28,8,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0.0,110.0,0,Transient,104.72,0,1,Canceled,2015-07-08,Amanda Myers,AmandaMyers@att.com,692-752-0185,************8187
219,Resort Hotel,1,1,2015,July,28,8,0,1,2,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0.0,110.0,0,Transient,104.72,0,1,Canceled,2015-07-08,Joshua Patrick,JoshuaPatrick@xfinity.com,868-836-9111,************9404
220,Resort Hotel,0,1,2015,July,28,8,0,2,2,0.0,0,BB,CHE,Corporate,Corporate,0,0,0,A,F,0,No Deposit,0.0,110.0,0,Transient,104.72,1,1,Check-Out,2015-07-10,Martin Mcknight,Mcknight.Martin17@comcast.net,880-037-2943,************5090
295,Resort Hotel,0,84,2015,July,28,11,1,1,2,0.0,0,HB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0.0,113.0,0,Transient,100.00,1,0,Check-Out,2015-07-13,Lisa Morgan,LMorgan@hotmail.com,645-017-6780,************3449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119119,City Hotel,0,40,2017,August,35,29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,0.0,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30,Carla Fischer,CFischer@att.com,979-981-4488,************8544
119122,City Hotel,0,40,2017,August,35,29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,0.0,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30,Valerie Ramirez,Ramirez.Valerie@verizon.com,265-792-0123,************2999
119123,City Hotel,0,40,2017,August,35,29,0,1,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,D,D,0,No Deposit,0.0,451.0,0,Transient,95.00,0,0,Check-Out,2017-08-30,Lisa Cantrell,LCantrell42@gmail.com,898-040-5133,************7000
119124,City Hotel,0,0,2017,August,35,29,0,1,1,0.0,0,BB,PRT,Complementary,Corporate,0,0,0,A,A,0,No Deposit,0.0,72.0,0,Transient,0.00,0,2,Check-Out,2017-08-30,Erin Hatfield,EHatfield@aol.com,868-960-2621,************8605
119248,City Hotel,0,22,2017,August,35,29,0,3,1,0.0,0,BB,PRT,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0.0,485.0,0,Transient,75.00,0,4,Check-Out,2017-09-01,Tammy Hughes,Tammy_H@outlook.com,992-779-1181,************3098

In [26]:
df["company"].value_counts()

40.0     927
223.0    784
67.0     267
45.0     250
153.0    215
        ...
104.0      1
531.0      1
160.0      1
413.0      1
386.0      1
Name: company, Length: 352, dtype: int64

In [27]:
df.loc[df['company'].isna(), 'company'] = 0.0  #No company

In [28]:
nan_ser = df.isna().sum().sort_values(ascending=False)
nan_ser[nan_ser > 0]

Series([], dtype: int64)

### Duplicates

In [29]:
df.duplicated().any()

False

In [43]:
df[df[['email']].duplicated(keep=False)].sort_values(['email'])

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
19317,Resort Hotel,0,3,2015,December,50,12,0,1,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,D,0,No Deposit,330.0,0.0,0,Transient-Party,29.00,0,1,Check-Out,2015-12-13,Amanda Anderson,AAnderson@comcast.net,960-293-6243,************6798
8377,Resort Hotel,1,56,2016,September,39,24,2,4,2,2.0,0,BB,IRL,Online TA,TA/TO,0,0,0,G,G,0,No Deposit,240.0,0.0,0,Transient,164.17,0,0,Canceled,2016-07-30,Anne Anderson,AAnderson@comcast.net,334-376-1771,************5963
104112,City Hotel,0,30,2017,January,1,2,1,3,1,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,88.40,0,3,Check-Out,2017-01-06,Andrew Arnold,AArnold@xfinity.com,521-597-9270,************4956
104399,City Hotel,0,20,2017,January,2,9,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,91.88,1,1,Check-Out,2017-01-13,Ashley Arnold,AArnold@xfinity.com,595-343-3390,************9048
10549,Resort Hotel,1,26,2017,March,11,14,0,5,2,0.0,0,HB,PRT,Direct,Direct,0,0,0,E,E,0,No Deposit,0.0,0.0,0,Transient-Party,80.00,0,0,Canceled,2017-02-16,Alexis Ayala,AAyala@yandex.com,413-653-4131,************6950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5658,Resort Hotel,1,46,2016,May,20,8,2,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,242.0,0.0,0,Transient,95.00,0,0,Canceled,2016-04-29,Zachary Johnson,Zachary.J@zoho.com,387-207-1958,************3742
98154,City Hotel,0,276,2016,September,39,22,0,3,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,0.0,178,Transient-Party,116.33,0,0,Check-Out,2016-09-25,Zachary Martinez,Zachary.M@xfinity.com,626-876-0069,************9579
95260,City Hotel,0,110,2016,August,34,14,2,1,2,0.0,0,SC,GBR,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,28.0,0.0,0,Transient,63.75,0,0,Check-Out,2016-08-17,Zachary Shields MD,Zachary.M@xfinity.com,694-112-4587,************5379
98411,City Hotel,0,3,2016,September,40,25,2,2,1,0.0,0,BB,PRT,Complementary,Direct,0,0,0,A,A,0,No Deposit,0.0,45.0,0,Transient,0.00,0,0,Check-Out,2016-09-29,Zachary Johnson,Zachary_Johnson@protonmail.com,826-983-3603,************6605
49604,City Hotel,1,25,2016,April,16,15,2,3,2,0.0,0,HB,ESP,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,149.40,0,0,Canceled,2016-04-04,Zachary Johnson,Zachary_Johnson@protonmail.com,179-398-4696,************1681

In [41]:
df[df[['phone-number']].duplicated(keep=False)].sort_values(['phone-number'])

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date, name, email, phone-number, credit_card]
Index: []

In [36]:
df['email'].nunique()

115889

In [44]:
df[df[['name']].duplicated(keep=False)].sort_values(['name'])

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
92717,City Hotel,0,103,2016,July,28,6,1,4,2,0.0,0,SC,DEU,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,83.0,0.0,0,Transient,78.20,0,0,Check-Out,2016-07-11,Aaron Adams,AaronAdams@zoho.com,574-840-4715,************3860
39232,Resort Hotel,0,253,2017,August,32,9,0,3,3,1.0,0,BB,GBR,Direct,Direct,0,0,0,H,H,2,No Deposit,250.0,0.0,0,Transient,236.10,1,1,Check-Out,2017-08-12,Aaron Adams,Aaron_A@verizon.com,110-703-6597,************3930
32121,Resort Hotel,0,41,2017,January,3,17,0,0,1,0.0,0,Undefined,PRT,Groups,Direct,0,0,0,A,A,1,No Deposit,0.0,0.0,0,Transient-Party,0.00,0,0,Check-Out,2017-01-17,Aaron Adams,Aaron.Adams@zoho.com,340-616-3384,************8863
29436,Resort Hotel,0,0,2016,October,44,23,2,4,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,96.0,0.0,0,Group,46.00,0,1,Check-Out,2016-10-29,Aaron Adams,AAdams94@comcast.net,543-383-8949,************7670
33012,Resort Hotel,0,19,2017,February,6,9,0,3,2,0.0,0,BB,GBR,Offline TA/TO,TA/TO,0,0,0,E,E,0,No Deposit,171.0,0.0,0,Transient,50.00,0,0,Check-Out,2017-02-12,Aaron Allen,AAllen@mail.com,550-241-5926,************3992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316,Resort Hotel,1,53,2016,November,46,11,2,4,2,0.0,0,HB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,241.0,0.0,0,Transient,49.90,0,1,Canceled,2016-10-11,Zachary Wood,ZacharyWood93@protonmail.com,641-983-0493,************4447
61717,City Hotel,1,313,2016,December,52,23,3,7,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,77.69,0,0,Canceled,2016-02-16,Zachary Young,Zachary_Young@outlook.com,276-752-2336,************4254
43065,City Hotel,0,135,2015,September,38,14,1,2,2,0.0,0,BB,CN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,0.0,0,Transient-Party,90.00,0,0,Check-Out,2015-09-17,Zachary Young,Zachary_Y@att.com,749-400-4305,************2792
98581,City Hotel,0,100,2016,September,40,28,0,4,2,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,26.0,0.0,0,Transient-Party,140.00,0,1,Check-Out,2016-10-02,Zoe Wu,Zoe.W89@mail.com,641-794-3600,************7369
15061,Resort Hotel,0,0,2017,May,19,11,0,1,2,0.0,0,BB,PRT,Direct,Direct,1,0,1,A,C,0,No Deposit,0.0,0.0,0,Transient,80.00,1,1,Check-Out,2017-05-12,Zoe Wu,Zoe_Wu95@hotmail.com,107-380-9284,************3221

In [45]:
df[df[['credit_card']].duplicated(keep=False)].sort_values(['credit_card'])

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
108638,City Hotel,0,132,2017,March,13,26,2,3,1,0.0,0,BB,BRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,0.0,0,Transient,61.52,0,1,Check-Out,2017-03-31,Kimberly Bennett,Kimberly_Bennett67@att.com,729-190-6211,************1000
105512,City Hotel,0,23,2017,January,5,29,4,9,1,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,0.0,0,Transient,43.53,0,1,Check-Out,2017-02-11,Gregory Price,Gregory_P67@mail.com,827-423-3503,************1000
41848,City Hotel,1,50,2015,August,35,25,0,4,1,0.0,0,BB,PRT,Groups,TA/TO,0,0,0,A,D,1,No Deposit,1.0,0.0,0,Transient-Party,60.00,0,0,Canceled,2015-08-24,Luke Reid,LReid@outlook.com,349-455-6829,************1000
86941,City Hotel,0,26,2016,April,16,11,1,0,2,0.0,0,SC,CN,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,89.00,0,1,Check-Out,2016-04-12,Linda Ruiz,Linda.Ruiz@outlook.com,510-016-5512,************1000
88548,City Hotel,0,21,2016,May,19,7,0,1,2,0.0,0,BB,FRA,Direct,Direct,0,0,0,D,D,0,No Deposit,14.0,0.0,0,Transient,152.00,0,0,Check-Out,2016-05-08,Steven Ray,Ray_Steven@yahoo.com,323-494-1848,************1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64905,City Hotel,1,1,2017,March,12,20,1,3,2,0.0,0,BB,CHN,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0.0,0,Transient,138.15,0,0,Canceled,2017-03-19,Alexis Castillo,Alexis.C@xfinity.com,528-179-2345,************9999
38693,Resort Hotel,0,210,2017,July,30,24,1,2,2,1.0,0,HB,HUN,Online TA,TA/TO,0,0,0,A,A,1,No Deposit,240.0,0.0,0,Transient-Party,218.75,0,1,Check-Out,2017-07-27,Jacob Rivera,Rivera.Jacob@protonmail.com,288-254-5438,************9999
99532,City Hotel,0,2,2016,October,42,10,1,3,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,D,A,0,No Deposit,9.0,0.0,0,Transient,175.00,0,0,Check-Out,2016-10-14,Amber Solis,Amber.S@hotmail.com,526-308-9758,************9999
46970,City Hotel,1,16,2016,January,5,30,2,1,2,0.0,0,BB,CHE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,88.33,0,0,Canceled,2016-01-27,Cheryl Smith,Cheryl.Smith@zoho.com,918-327-9377,************9999
107492,City Hotel,0,24,2017,March,11,12,1,0,2,0.0,0,BB,CHN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,22.0,0.0,0,Transient,80.00,0,1,Check-Out,2017-03-13,Belinda Alvarez,Alvarez_Belinda11@zoho.com,397-926-1147,************9999

Vemos sospechoso los datos del cliente, tanto name, email, phone-number y credit_card

In [47]:
df = df.drop(["name", "email", "phone-number", "credit_card"], axis=1)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,0.0,0.0,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,0.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

### Outliers

In [48]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_year,119390.0,2016.156554,0.707476,2015.00,2016.00,2016.000,2017.0,2017.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119390.0,0.103886,0.398555,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
is_repeated_guest,119390.0,0.031912,0.175767,0.00,0.00,0.000,0.0,1.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
company,119390.0,10.775157,53.943884,0.00,0.00,0.000,0.0,543.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [50]:
df['is_canceled'].value_counts()

0    75166
1    44224
Name: is_canceled, dtype: int64

### Save CSV

In [51]:
df.to_csv('data/hotel_booking_cleaning.csv', index=False)